Update README.md
elementary/greeter pull request #587
Opened 2021-12-07 20:54 UTC by marmeladapk

Updated required dependencies in readme.

2021-12-10 22:10 UTC, danrabbit requested changes
Hey thanks for noticing this! Just one comment

2021-12-10 22:10 UTC, danrabbit commented on README.md
> +* libwingpanel-3.0-dev
I think we actually dropped the libwingpanel dep completely since we use the panel as its own process now

2021-12-26 09:27 UTC, marmeladapk commented on README.md
> +* libwingpanel-3.0-dev
I checked and removed wingpanel-dev package, greeter still built.

2022-01-03 20:01 UTC, danrabbit approved these changes
thanks!

2022-01-03 20:01 UTC, merged