blured clutter canvas
elementary/greeter pull request #623
Opened 2022-10-31 15:20 UTC by torikulhabib

replace https://github.com/elementary/greeter/pull/549

2022-10-31 17:36 UTC, vjr commented
Hi @torikulhabib  is this the blurred greeter wallpaper background?

I like the idea +1 from me but I might only be able to try it this weekend

2022-10-31 19:53 UTC, danirabbit requested changes
Left a couple of comments

Another problem I'm noticing in this branch is that the panel seems to be opaque when it would otherwise be transparent without blur. This seems counter-intuitive

I would also suggest increasing the blur radius. To my eye, `10` looks more like poor upscaling than an intentional blur

2022-10-31 19:53 UTC, danirabbit commented on compositor/SystemBackground.vala
> +            var surface = new Granite.Drawing.BufferSurface (pixbuf.width, pixbuf.height);
`Granite.Drawing.BufferSurface` was removed from Granite 7, so if you want to use it here you should add it as we did in Gala: https://github.com/elementary/gala/pull/1428

2022-11-01 01:53 UTC, torikulhabib commented on compositor/SystemBackground.vala
> +            var surface = new Granite.Drawing.BufferSurface (pixbuf.width, pixbuf.height);
ok

2022-11-12 17:16 UTC, vjr commented
Hi @torikulhabib I tried this PR in VM and also my actual v7 installation and I like the concept but some observations for improvements...

* The background is not scaled correctly on my HiDPI monitor - it's too large - only part of the background is visible.
* The fade should be a "crossfade" or "blend" I guess from one user's background to the other user's background - currently upon switching the user it starts from blank and fades-in.
* The performance is jerky (not smooth) and this is probably due to the code trying to iterate the `fadebg` steps from 1 to 10 "manually" instead of I guess animating it?

I'm not familiar with the code to do pixbuf crossfading - could you look at the code in gala and try something similar here? If you see the wallpaper fading when you change your wallpaper in the desktop settings, it's very smooth and pleasant - if you try to re-use that code the greeter would look nice too.

Thanks for this PR! Personally I hope this idea gets implemented in the greeter :-)

2022-11-13 06:43 UTC, vjr commented
@torikulhabib the scaling is fixed but I would still suggest trying to steal the code from gala and modify it a little to add the crossfade and blur? I might try it myself but not too familiar with UI coding.

2022-11-14 07:57 UTC, tintou requested changes

2022-11-14 07:57 UTC, tintou commented on compositor/SystemBackground.vala
> +                    });
Instead of fading manually, you have to use the `Clutter.Transition` API bound the the Actor

2023-02-13 16:30 UTC, BAProductions commented
No working For Me

2023-02-14 14:13 UTC, BAProductions commented
> replace #549
I just made a pr agent your repos to fix the wallpaper no showing up on my VM.

2024-02-20 22:10 UTC, closed without merging