Fix double login
elementary/greeter pull request #624
Opened 2022-11-12 13:31 UTC by vjr

Fixes https://github.com/elementary/triage/issues/92

2022-11-12 13:39 UTC, vjr commented
@elementary/desktop-developers 

Any suggestions for how to get greeter to restart itself or via restart lightdm?

See the code block starting here: https://github.com/elementary/greeter/pull/624/files#diff-3d3c3150c12cf12f07b12828137c3dc9478f9a12c21ad40905aef57c8e12255aR519

When I try to trigger lightdm restart I get the error "this requires interactive permissions" so any pointers on how to resolve this?

Initial setup uses the systemd `hostname1` dbus interface and the methods there have a boolean parameter to set interactive mode false but I couldn't see something similar for the `systemd1` dbus interface methods.

I think this draft PR with its current approach might be an acceptable way to resolve the issue but if anyone has a better approach I can give that a shot too.

Thanks!

2022-11-13 10:19 UTC, vjr commented
I tried (probably incorrectly) to use the `sd_bus_set_allow_interactive_authorization ()` libsystemd API , still get the error.

@tintou

2022-11-25 09:09 UTC, davidmhewitt submitted a review, later dismissed

2022-11-25 09:09 UTC, davidmhewitt commented on data/io.elementary.greeter.policy.in
> +      <allow_active>yes</allow_active>
I don't like the idea of having a policy installed the system that allows any process running as any user to manage all systemd units.

There are ways of scoping policies down to specific users and even checking which systemd units we are trying to manage.

So before this is merged, I'd like to see this policy restricted to only what is necessary (i.e. only the lightdm user can use it, it only applies to restarting the lightdm service, and possibly even can only be requested by the lightdm executable)

Useful references:
https://wiki.archlinux.org/title/Polkit
https://www.freedesktop.org/software/polkit/docs/latest/polkit.8.html

2022-11-25 09:42 UTC, vjr commented on data/io.elementary.greeter.policy.in
> +      <allow_active>yes</allow_active>
Thanks for the review @davidmhewitt 

@meisenzahl  could you please help here again? Feel free to push to this branch itself instead of opening a new PR.

2022-12-23 20:49 UTC, vjr commented on data/io.elementary.greeter.policy.in
> +      <allow_active>yes</allow_active>
@davidmhewitt  @elementary/desktop-developers  addressed the polkit lax permissions issue...

2022-12-23 21:07 UTC, vjr commented
@meisenzahl the rules file wasn't working because jammy still has an older version 0.105 of polkit which doesn't support rules/javascript! Came across this while searching the web while troubleshooting the issue.

2022-12-24 05:02 UTC, meisenzahl requested changes
@vjr nice work! Works as intended.

I have some comments where I'm not sure what would be best practice at this place.

@davidmhewitt I would be very happy about another review from you, since you have clearly more knowledge of Polkit 😁

2022-12-24 15:00 UTC, vjr commented on data/io.elementary.greeter.pkla
> +ResultAny=no
agreed

2022-12-24 15:04 UTC, vjr commented on data/meson.build
> +)
I suggest keeping the existing RDNN format as mentioned in the "man pklocalauthority" notes and not prepending with that number. It is already installed into `10-vendor.d` which is intended (as the name implies and noted in the manpages) for vendors. But we'll see comments from reviewers.

2022-12-24 15:05 UTC, vjr commented on src/MainWindow.vala
> +
addressed

2022-12-24 15:05 UTC, vjr commented on src/meson.build
> +polkit_dep = dependency('polkit-gobject-1')
addressed.

2022-12-24 15:05 UTC, vjr commented on src/meson.build
> +    dependencies: [ actservice_dep, gobject_dep, glib_dep, gtk_dep, granite_dep, hdy_dep, polkit_dep, lightdm_dep ],
addressed.

2023-01-29 20:40 UTC, danirabbit commented
@tintou fixed this with a patch in Lightdm. So we don't need to restart this anymore :)

2023-01-29 20:40 UTC, closed without merging