Fix double login authentication
elementary/greeter pull request #628
Opened 2022-11-22 12:57 UTC by meisenzahl

2022-11-22 13:03 UTC, mariadb-vishalrao commented
Thanks for this. I can test and merge it only maybe in a couple of days time FYI.

2022-11-22 13:05 UTC, vjr commented
Oops, previous comment was supposed to be from me haha.

2022-11-22 20:24 UTC, danirabbit requested changes

2022-11-22 20:24 UTC, danirabbit commented on data/io.elementary.greeter.policy.in
> +    <message>Authentication is required to restart Greeter</message>
I guess this theoretically shouldn't show a polkit dialog, but the user facing name we use here is "Login & Lock Screen" instead of "Greeter"
```suggestion
    <description>Restart the Login & Lock screen</description>
    <message>Permission is needed to restart the Login & Lock Screen</message>
```

2022-11-25 07:15 UTC, vjr approved these changes
Yep... LGTM! works well too. Will merge this into my branch and update my PR to clean it up a bit and mark it ready for review shortly.

2022-11-25 07:15 UTC, merged