Support dark mode
elementary/greeter pull request #684
Opened 2023-09-02 10:49 UTC by lenemter

To do:
[] Remove duplicate objects
[] Test this more

2023-09-02 13:03 UTC, BAProductions commented
Close my commit well

2024-01-30 00:27 UTC, danirabbit commented on src/PantheonAccountsServicePlugin.vala
> +    public abstract Coordinates prefer_dark_last_coordinates { get; set; }
Same comment as settings daemon about having only a single `last coordinates` that we share for everything

2024-01-30 16:46 UTC, danirabbit submitted a review, later dismissed
:rocket:

2024-01-31 00:16 UTC, danirabbit commented
Testing this with the latest settings-daemon, I am now getting a blank screen on the greeter :grimacing: Does this need to be updated too?

2024-01-31 00:18 UTC, lenemter commented
That's weird. Have you installed https://github.com/elementary/wingpanel/pull/499 by any chance?

2024-02-03 10:37 UTC, lenemter commented
I fixed a bug that prevented setting user preferences, everything should work as expected now.

2024-02-05 17:32 UTC, danirabbit commented
Sorry for taking a while to respond! Just tried again on a relatively clean OS 8 install where I have not had that wingpanel branch and I'm still getting a blank screen with this branch

2024-02-08 05:19 UTC, lenemter commented
@danirabbit Not sure what might have caused that. Can you send me logs from /var/log/lightdm/seat0-greeter.log please?

2024-02-13 18:09 UTC, danirabbit commented
@lenemter sorry for taking a while to follow up!

`(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.863: g_variant_new_string: assertion 'string != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.863: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.863: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:05.863: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.863: g_variant_get_type_string: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:05.863: g_settings_set_value: key 'document-font-name' in 'org.gnome.desktop.interface' expects type 's', but a GVariant of type '(null)' was given

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.863: g_variant_unref: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.865: g_variant_new_string: assertion 'string != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.865: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.865: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:05.865: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.865: g_variant_get_type_string: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:05.865: g_settings_set_value: key 'font-name' in 'org.gnome.desktop.interface' expects type 's', but a GVariant of type '(null)' was given

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.865: g_variant_unref: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.866: g_variant_new_string: assertion 'string != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.866: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.866: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:05.866: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.866: g_variant_get_type_string: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:05.866: g_settings_set_value: key 'monospace-font-name' in 'org.gnome.desktop.interface' expects type 's', but a GVariant of type '(null)' was given

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:05.866: g_variant_unref: assertion 'value != NULL' failed

** (io.elementary.greeter:39487): CRITICAL **: 10:02:05.879: MainWindow.vala:350: prompt: `Password: ' (1)

** (io.elementary.greeter:39487): CRITICAL **: 10:02:06.698: MainWindow.vala:350: prompt: `Password: ' (1)

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.364: g_variant_new_string: assertion 'string != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.364: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.364: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:07.364: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.364: g_variant_get_type_string: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:07.364: g_settings_set_value: key 'document-font-name' in 'org.gnome.desktop.interface' expects type 's', but a GVariant of type '(null)' was given

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.364: g_variant_unref: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.367: g_variant_new_string: assertion 'string != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.367: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.367: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:07.367: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.367: g_variant_get_type_string: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:07.367: g_settings_set_value: key 'font-name' in 'org.gnome.desktop.interface' expects type 's', but a GVariant of type '(null)' was given

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.367: g_variant_unref: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.369: g_variant_new_string: assertion 'string != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.369: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.369: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:07.369: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.369: g_variant_get_type_string: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:07.369: g_settings_set_value: key 'monospace-font-name' in 'org.gnome.desktop.interface' expects type 's', but a GVariant of type '(null)' was given

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:07.369: g_variant_unref: assertion 'value != NULL' failed

** (io.elementary.greeter:39487): CRITICAL **: 10:02:07.379: MainWindow.vala:350: prompt: `Password: ' (1)

** (io.elementary.greeter:39487): CRITICAL **: 10:02:08.084: MainWindow.vala:350: prompt: `Password: ' (1)

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:08.866: g_variant_new_string: assertion 'string != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:08.866: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:08.866: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:08.866: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:08.866: g_variant_get_type_string: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:08.866: g_settings_set_value: key 'document-font-name' in 'org.gnome.desktop.interface' expects type 's', but a GVariant of type '(null)' was given

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:08.866: g_variant_unref: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:08.868: g_variant_new_string: assertion 'string != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:08.868: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:08.868: g_variant_ref_sink: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:08.868: g_settings_schema_key_type_check: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:08.868: g_variant_get_type_string: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-GIO-CRITICAL **: 10:02:08.868: g_settings_set_value: key 'font-name' in 'org.gnome.desktop.interface' expects type 's', but a GVariant of type '(null)' was given

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:08.868: g_variant_unref: assertion 'value != NULL' failed

(io.elementary.greeter:39487): GLib-CRITICAL **: 10:02:08.878: [...]

2024-05-23 15:42 UTC, zeebok commented
@lenemter There is a conflict to resolve now

2024-06-24 14:52 UTC, zeebok commented
I am seeing the same compiler errors as the checks

2024-07-03 19:09 UTC, zeebok commented on src/Application.vala
>      var settings_daemon = new Greeter.SettingsDaemon ();
```suggestion
   settings_daemon = new Greeter.SettingsDaemon ();
```

2024-07-04 07:05 UTC, tintou requested changes
a few nits

2024-07-04 07:05 UTC, tintou commented on src/Application.vala
> +        portals = new Greeter.SubprocessSupervisor ({"/usr/libexec/xdg-desktop-portal"});
It is unclear to me why you need to spawn this?

2024-07-04 07:05 UTC, tintou commented on src/Application.vala
> +        settings_daemon = new Greeter.SubprocessSupervisor ({"io.elementary.settings-daemon"});
Also unclear?

2024-07-04 07:05 UTC, tintou commented on src/Cards/UserCard.vala
> +            greeter_act.prefers_color_scheme = prefers_color_scheme;
```suggestion
            if (changed_properties.lookup ("PrefersColorScheme", "i", out prefers_color_scheme)) {
                greeter_act.prefers_color_scheme = prefers_color_scheme;
            }
```

2025-05-09 19:32 UTC, closed without merging