Cleanup
elementary/greeter pull request #696
Opened 2024-01-28 06:32 UTC by lenemter

* Avoid syncing animations (not sure how they might get unsynced)
* Avoid using actions
* Get rid of `index_delta` and `nex_delta` stuff
* Cleanup keypress handling

2024-01-29 17:38 UTC, danirabbit requested changes
Can you resolve conflicts please? :)

2024-01-29 17:38 UTC, danirabbit commented on src/Cards/UserCard.vala
> -        form_revealer.size_allocate.connect ((alloc) => {
I think originally this was meant to sync the animation of the entry being revealed with the animation of the card switching. But it seems like maybe we broke that. Not sure if it's worth trying to fix instead?

2024-02-08 05:15 UTC, lenemter commented on src/Cards/UserCard.vala
> -        form_revealer.size_allocate.connect ((alloc) => {
I think it's a tricky thing to do with Gtk.Revealer + Hdy.Carousel. Maybe worth looking into this after Gtk4 port?

2024-02-08 05:15 UTC, lenemter commented
@danirabbit Done

2024-02-13 18:03 UTC, danirabbit approved these changes
:rocket:

2024-02-13 18:03 UTC, merged